version: '3.8'

services:
  app:
    image: node:18-alpine
    container_name: my-node-app
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: sh -c "npm install && npm start"
